<#
    .SYNOPSIS
    Monolithic PowerShell $PROFILE - modular components sourced into single session.

    .DESCRIPTION
    A PowerShell profile composed of smaller, maintainable component files:
    - namespaces.ps1: Type shortcuts
    - psreadline-handlers.ps1: Advanced key bindings (deferred)
    - prompt.ps1: Prompt initialization (Starship/Oh-My-Posh/Default)
    - shell-completions.ps1: CLI tool completions
    - aliases.ps1: Unix-like aliases and functions
    - software-init.ps1: Third-party tool initialization
    - functions/*.ps1: Custom function definitions
    
    All components must be in the ProfileComponents subdirectory within the profile directory.
    The installer (Install-MonoProfile.ps1) copies all necessary files to the profile directory.
    
    CONFIGURATION:
    Set $PromptHandler to choose your prompt:
    - "starship": Use Starship prompt
    - "oh-my-posh": Use Oh-My-Posh prompt  
    - "default" or $null: Use custom default prompt
#>

## Measure IMMEDIATELY when profile starts
# $VeryFirstProfileTime = Get-Date
# Write-Host "Profile code executing at: $($VeryFirstProfileTime)" -ForegroundColor Cyan

## Start profile timing
$ProfileStartTime = Get-Date

## Get the profile directory and ProfileComponents subdirectory
$ProfileDir = Split-Path -Path $PROFILE -Parent
$ComponentsDir = Join-Path $ProfileDir "ProfileComponents"

####################
# CONFIGURATION    #
####################

## Add custom modules directory to module path for auto-discovery
$CustomModulesPath = Join-Path $ProfileDir "Modules\Custom"
if (Test-Path $CustomModulesPath) {
    $env:PSModulePath = "$CustomModulesPath;$env:PSModulePath"
}

## Load prompt configuration (generated by Install-MonoProfile.ps1)
## If prompt-config.ps1 doesn't exist, $PromptHandler will be unset and
## the prompt.ps1 component will use the default prompt handler
$PromptConfigPath = Join-Path $ProfileDir "prompt-config.ps1"
if (Test-Path $PromptConfigPath) {
    . $PromptConfigPath
}

## Source all component files
$components = @(
    'namespaces.ps1'
    # 'psreadline-handlers.ps1'  # Deferred - loads in background via OnIdle
    'prompt.ps1'
    # 'shell-completions.ps1'    # Deferred - loads in background via OnIdle
    'aliases.ps1'
    'software-init.ps1'
)

foreach ( $component in $components ) {
    $componentPath = Join-Path $ComponentsDir $component
    if ( Test-Path $componentPath ) {
        try {
            # Measure component load time
            # $compStart = Get-Date

            . $componentPath
            
            ## Print components that take longer than threshold to load
            # $compEnd = Get-Date
            # $compTime = ($compEnd - $compStart).TotalMilliseconds
            # if ($compTime -gt 50) {
            #     Write-Host "  $component - ${compTime}ms" -ForegroundColor Yellow
            # }
        }
        catch {
            Write-Warning "Failed to load $component : $($_.Exception.Message)"
        }
    }
    else {
        Write-Warning "Component not found: $componentPath"
    }
}

## Defer PSReadLine handlers to background for faster startup
$psReadLineHandlersPath = Join-Path $ComponentsDir "psreadline-handlers.ps1"
if (Test-Path $psReadLineHandlersPath) {
    $null = Register-EngineEvent -SourceIdentifier PowerShell.OnIdle -MaxTriggerCount 1 -Action ([scriptblock]::Create(@"
        try {
            . '$($psReadLineHandlersPath -replace "'", "''")'
        }
        catch {
            Write-Warning "Failed to load deferred PSReadLine handlers: `$(`$_.Exception.Message)"
        }
"@))
}

## Defer shell completions to background (not needed until user presses Tab)
$shellCompletionsPath = Join-Path $ComponentsDir "shell-completions.ps1"
if (Test-Path $shellCompletionsPath) {
    $null = Register-EngineEvent -SourceIdentifier PowerShell.OnIdle -MaxTriggerCount 1 -Action ([scriptblock]::Create(@"
        try {
            . '$($shellCompletionsPath -replace "'", "''")'
        }
        catch {
            Write-Warning "Failed to load deferred shell completions: `$(`$_.Exception.Message)"
        }
"@))
}

## Defer posh-git to background for faster startup
#  Note: availability check moved inside OnIdle to avoid synchronous Get-Module -ListAvailable scan
$null = Register-EngineEvent -SourceIdentifier PowerShell.OnIdle -MaxTriggerCount 1 -Action {
    try {
        if (Get-Module -ListAvailable -Name posh-git) {
            Import-Module posh-git -ErrorAction Stop
            # Disable posh-git prompt (Starship handles the prompt)
            $GitPromptSettings.EnablePromptStatus = $false
        }
    }
    catch {
        Write-Warning "Failed to import posh-git: $($_.Exception.Message)"
    }
}

#############
# Functions #
#############

## Load custom functions - uses consolidated cache for performance
#  On AV-protected machines, loading 1 cached file vs 75+ individual files is significantly faster
$FunctionsDir = Join-Path $ComponentsDir "functions"
$FunctionsCacheFile = Join-Path $ComponentsDir ".functions-cache.ps1"

if (Test-Path $FunctionsCacheFile) {
    ## Use consolidated cache file (1 file read instead of 75+)
    try {
        . $FunctionsCacheFile
    }
    catch {
        Write-Warning "Failed to load functions cache, falling back to individual files: $($_.Exception.Message)"
        Remove-Variable FunctionsCacheFile -ErrorAction SilentlyContinue
    }
}

## Fallback: load individual function files if cache doesn't exist or failed to load
if (-not (Test-Path variable:\FunctionsCacheFile) -or -not (Test-Path $FunctionsCacheFile)) {
    if (Test-Path $FunctionsDir) {
        $functionFiles = Get-ChildItem -Path $FunctionsDir -Filter "*.ps1" -File -Recurse
        foreach ($funcFile in $functionFiles) {
            try {
                . $funcFile.FullName
            }
            catch {
                Write-Warning "Failed to load function $($funcFile.Name): $($_.Exception.Message)"
            }
        }
    }
}

## Provide a function to rebuild the consolidated function cache
function global:Update-FunctionCache {
    <#
        .SYNOPSIS
        Rebuild the consolidated function cache from individual function .ps1 files.

        .DESCRIPTION
        Reads all .ps1 files from ProfileComponents\functions\ and concatenates them into
        a single cache file. This dramatically improves startup performance by reducing
        file I/O operations, which is especially impactful on machines with antivirus scanning.

        Run this after adding, modifying, or removing function files to update the cache.
        The installer (Install-MonoProfile.ps1) generates this cache automatically.
    #>
    $functionsDir = Join-Path (Split-Path $PROFILE -Parent) "ProfileComponents\functions"
    $cacheFile = Join-Path (Split-Path $PROFILE -Parent) "ProfileComponents\.functions-cache.ps1"

    if (-not (Test-Path $functionsDir)) {
        Write-Warning "Functions directory not found: $functionsDir"
        return
    }

    $files = Get-ChildItem -Path $functionsDir -Filter "*.ps1" -File -Recurse
    $sb = [System.Text.StringBuilder]::new(65536)
    $null = $sb.AppendLine("# Auto-generated function cache - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    $null = $sb.AppendLine("# Regenerate with: Update-FunctionCache")
    $null = $sb.AppendLine("# Source: $functionsDir")
    $null = $sb.AppendLine()

    foreach ($f in $files) {
        $relativePath = $f.FullName.Replace($functionsDir, '').TrimStart('\')
        $null = $sb.AppendLine("##region $relativePath")
        $null = $sb.AppendLine([System.IO.File]::ReadAllText($f.FullName))
        $null = $sb.AppendLine("##endregion")
        $null = $sb.AppendLine()
    }

    [System.IO.File]::WriteAllText($cacheFile, $sb.ToString())
    Write-Host "Function cache rebuilt: $cacheFile ($($files.Count) files consolidated)" -ForegroundColor Green
}

##############################################################
# PROFILE load finished                                      #
# Leave this at the bottom, and don't put anything after it. #
##############################################################

## End profile initialization timer
$ProfileEndTime = Get-Date
## Calculate profile init time
$ProfileInitTime = $ProfileEndTime - $ProfileStartTime
## Store timing in global variable (can check with $global:ProfileLoadTime)
$global:ProfileLoadTime = $ProfileInitTime.TotalSeconds

## No code below this line
