# Module initialization file
# This file is auto-generated by Install-CustomProfile.ps1
# Do not edit manually - changes will be overwritten on next install

# Modules to load immediately on profile startup
$immediate_load = @()

# Modules to load lazily (on-demand via proxy functions)
$lazy_load = @()
